<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>poti</string>
	</array>
	<key>name</key>
	<string>Potigol</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Comentario Bloco</string>
			<key>match</key>
			<string>\#.*$</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>([a-zA-Z0-9_])+\(</string>
			<key>comment</key>
			<string>Funcao</string>
			<key>contentName</key>
			<string>variable.parameter</string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>entity.name.function</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>tipo</string>
			<key>match</key>
			<string>\btipo\b</string>
			<key>name</key>
			<string>storage.type</string>
		</dict>
		<dict>
			<key>comment</key>
			<false/>
		</dict>
		<dict>
			<key>comment</key>
			<string>Modificador</string>
			<key>match</key>
			<string>\b(var)\b</string>
			<key>name</key>
			<string>storage.modifier</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>inteiro</string>
			<key>match</key>
			<string>\b([0-9])+(\.([0-9])+)?|(verdadeiro|falso)\b</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>tipos</string>
			<key>match</key>
			<string>\b(Inteiro|Numero|Texto|Logico|Caractere)\b</string>
			<key>name</key>
			<string>entity.name.type</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Palavras Chave</string>
			<key>match</key>
			<string>\b(se|entao|então|senao|senão|fim|enquanto|para|de|em|passo|gere|senaose|senãose|ate|até|caso|escolha|faca|faça|tipo)\b</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Operadores</string>
			<key>match</key>
			<string>\b(nao|não|e|ou|mod|div|formato)\b|(,|\.|=|==|\:\:|\:=|&lt;=|&lt;&gt;|&lt;|&gt;=|=&gt;|&gt;|\+|\-|\*|\/|\(|\)|\:|\^|\[|\])</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>var</string>
			<key>match</key>
			<string>\b[a-zA-Z][a-zA-Z0-9_]*\b</string>
			<key>name</key>
			<string>variable.language</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Texto</string>
			<key>match</key>
			<string>\".*\"</string>
			<key>name</key>
			<string>string.interpolated</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.poti</string>
	<key>uuid</key>
	<string>9f9bbe3d-fecc-4afa-838d-70a5ebdc01cc</string>
</dict>
</plist>
